### PR TITLE
Fix bug with `:ObsidianOpen`

### LINKED ISSUE #19: Can't seem to open vault directory.
### 🐛 Describe the bug

when I run `ObsidianOpen` from my vault directory I get `[Obsidian] couldn't find an Obsidian vault`

I tried to debug it, and from what I can see it only check for `.obsidian` folder in all the parents of the `dir` option, but on in the `dir` itself. see `client.valut` at https://github.com/epwalsh/obsidian.nvim/blob/38ba031ca19cdbe296ae18a401ace5a82e770b1c/lua/obsidian/init.lua#L115

so I tried to enter one of the subdirectories, and it indeed worked.
this is clearly not optimal ;).

### Versions

NVIM v0.8.0-dev-1112-g6d557e324
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1663477808273.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
1.3.0%

### PR DESCRIPTION
**Pull request by epwalsh**
Fixes #19

### CODE REVIEW

File: lua/obsidian/init.lua [hunk 1]
```diff
@@ -116,12 +116,12 @@ client.vault = function(self)
   local vault_indicator_folder = ".obsidian"
   local dirs = self.dir:parents()
   table.insert(dirs, self.dir:absolute())
-  for _, parent in pairs(self.dir:parents()) do
+  for _, dir in pairs(dirs) do
```
Comment (vitaly) [inline lua/obsidian/init.lua:119]: This doesn't actually solve anything... `dirs` is equal to `self.dir:parents()`, so nothing is changed by this commit.

Comment (vitaly) [reply lua/obsidian/init.lua:119]: you need to consider the dir itself, in addition to it's parents. e.g. if the dir is `/a/b/c`, you are only looking at `c`'s parents `/a`, and `/a/b`

**Review by vitaly — COMMENTED** [review]
The bug wasn't fixed ;)

File: lua/obsidian/init.lua (hunk 1 above)
Comment (vitaly) [reply lua/obsidian/init.lua:119]: I'm not too good with lua, but may be something like
```lua
local dirs = { dir, unpack(self.dir:parents()) }
```
