### PR TITLE
fix(open): linux error spawning new obsidian process

### LINKED ISSUE #319: ObsidianOpen Can't Start a New Session
### 🐛 Describe the bug

When I try to run `:ObsidianOpen` on a file, Obsidian will throw an error with the exception in the picture below.

image

However, when I run `:ObsidianOpen` on a file while an existing Obsidian session is running, it works fine. I am on EndeavourOS running the AUR version of Obsidian (sourced from AppImage). Does this seem like a system problem, an Obsidian problem, or an obsidian.nvim problem? Is there a way to circumvent this easily, i.e. try to start an Obsidian session in the specified vault upon failure and then re-run the obsidian bin command with the file as input?

### Versions

lazy-lock.json:
```
{
  "LuaSnip": { "branch": "master", "commit": "82108e7e31cc6fc223cc5df5cae6d89f70bb199f" },
  "cmp-nvim-lsp": { "branch": "main", "commit": "5af77f54de1b16c34b23cba810150689a3a90312" },
  "cmp_luasnip": { "branch": "master", "commit": "05a9ab28b53f71d1aece421ef32fee2cb857a843" },
  "diffview.nvim": { "branch": "main", "commit": "3dc498c9777fe79156f3d32dddd483b8b3dbd95f" },
  "friendly-snippets": { "branch": "main", "commit": "69a2c1675b66e002799f5eef803b87a12f593049" },
  "gitsigns.nvim": { "branch": "main", "commit": "3e6e91b09f0468c32d3b96dcacf4b947f037ce25" },
  "lazy.nvim": { "branch": "main", "commit": "96584866b9c5e998cbae300594d0ccfd0c464627" },
  "lualine.nvim": { "branch": "master", "commit": "566b7036f717f3d676362742630518a47f132fff" },
  "mason-lspconfig.nvim": { "branch": "main", "commit": "0989bdf4fdf7b5aa4c74131d7ffccc3f399ac788" },
  "mason.nvim": { "branch": "main", "commit": "e110bc3be1a7309617cecd77bfe4bf86ba1b8134" },
  "neodev.nvim": { "branch": "main", "commit": "be8d4d4cab6c13c6a572269c9d6a63774baba9a0" },
  "neogit": { "branch": "master", "commit": "760d6d74c328ce2a38b02677bf5161999b992da2" },
  "nvim": { "branch": "main", "commit": "5e36ca599f4aa41bdd87fbf2c5aae4397ac55074" },
  "nvim-cmp": { "branch": "main", "commit": "538e37ba87284942c1d76ed38dd497e54e65b891" },
  "nvim-lspconfig": { "branch": "master", "commit": "796394fd19fb878e8dbc4fd1e9c9c186ed07a5f4" },
  "nvim-notify": { "branch": "master", "commit": "1576123bff3bed67bc673a3076e591abfe5d8ca9" },
  "nvim-tree.lua": { "branch": "master", "commit": "f1b3e6a7eb92da492bd693257367d9256839ed3d" },
  "nvim-treesitter": { "branch": "master", "commit": "8cd2b230174efbf7b5d9f49fe2f90bda6b5eb16e" },
  "nvim-web-devicons": { "branch": "master", "commit": "db0c864375c198cacc171ff373e76bfce2a85045" },
  "obsidian.nvim": { "branch": "main", "commit": "dbd81af68896a6276001dd9f65c7cb965b411338" },
  "plenary.nvim": { "branch": "master", "commit": "55d9fe89e33efd26f532ef20223e5f9430c8b0c0" },
  "telescope-fzf-native.nvim": { "branch": "main", "commit": "6c921ca12321edaa773e324ef64ea301a1d0da62" },
  "telescope.nvim": { "branch": "master", "commit": "d90956833d7c27e73c621a61f20b29fdb7122709" }
}
```

### PR DESCRIPTION
**Pull request by benelan**
The `ObsidianOpen` command failed to open the Obsidian app on Linux if it wasn't already running. After some troubleshooting I determined it is something related to the async module. 

Nothing jumped out at me in the plenary job initialization code, but using `vim.fn.jobstart()`, `vim.system()`, and `vim.uv.spawn()` all work. I went with jobstart for backwards compatibility. Let me know if I need to make any other changes, or feel free to adopt this patch however you see fit. Thanks for the great plugin!

Fix #319

### CODE REVIEW

**Comment by benelan** [comment]
I can also only make this change for Linux, if you'd prefer.

```lua
  if this_os == util.OSType.Linux then
    vim.fn.jobstart(cmd .. " " .. vim.fn.shellescape(table.concat(args, " ")), { detach = true })
  else
    run_job(cmd, args)
  end
```

**Comment by epwalsh** [comment]
@benelan I wonder if it has to do with running in a shell env vs no shell. I think the plenary `Job` runs without a shell, but `vim.fn.jobstart` would run in the shell when you pass the command as a string, instead of a list 🤔

File: lua/obsidian/commands/open.lua [hunk 1]
```diff
@@ -81,5 +80,6 @@ return function(client, data)
 
   assert(cmd)
   assert(args)
-  run_job(cmd, args)
+
+  vim.fn.jobstart(cmd .. " " .. vim.fn.shellescape(table.concat(args, " ")), { detach = true })
```
Comment (epwalsh) [inline lua/obsidian/commands/open.lua:84]: Apparently nvim recommends using `vim.system()` from Lua instead of `vim.fn.jobstart()` (see `:help jobstart`). I'm not entirely sure why but I guess I'd rather follow that recommendation then not.

Also would be good to report errors like `run_job()` will.

**Review by epwalsh — COMMENTED** [review]
Hey @benelan, thanks for this!

File: lua/obsidian/commands/open.lua (hunk 1 above)
Comment (benelan) [reply lua/obsidian/commands/open.lua:84]: Yeah I checked and unfortunately `vim.system()` isn't available in `v0.9`, so I used `vim.fn.jobstart()` for backwards compatibility. Should I throw a conditional in there to check the nvim version and use `vim.system()` if it is available?

I'll add in some error reporting either way.

Comment (epwalsh) [reply lua/obsidian/commands/open.lua:84]: Huh, okay in that case let's stick with `vim.fn.jobstart`. It looks like you can pass a callback there to capture stderr.

**Comment by benelan** [comment]
Alright, I added the logging! Opening obsidian with `xdg-open` writes to stderr even if the process doesn't fail. I confirmed this outside of neovim as well:

```sh
$ xdg-open "obsidian://open?vault=notes&file=monorepos.md" 2>&1 >/dev/null

[104469:0126/132841.090072:ERROR:node_bindings.cc(300)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

(obsidian:104469): Gtk-WARNING **: 13:28:41.206: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class
[104469:0126/132841.419062:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
```

I used on_exit instead and log if the code isn't 0.

I also tested passing a list to jobstart and it still worked. Here is the vim command for reference:

```vim
:exe jobstart(["xdg-open", "obsidian://open?vault=notes&file=monorepos.md"], {"detach": v:true})
```

File: lua/obsidian/commands/open.lua [hunk 2]
```diff
@@ -81,5 +82,13 @@ return function(client, data)
 
   assert(cmd)
   assert(args)
-  run_job(cmd, args)
+
+  vim.fn.jobstart(cmd .. " " .. table.concat(args, " "), {
+    detach = true,
+    on_exit = function(_, exit_code)
+      if exit_code ~= 0 then
+        log.err("open command's job failed with exit code '" .. exit_code .. "'")
```
Comment (epwalsh) [inline lua/obsidian/commands/open.lua:90]: Could you also log the final cmd string that was passed to `jobstart` when it fails?

**Review by epwalsh — COMMENTED** [review]
Awesome! Looks good. Just one more minor request and then we can get this merged!

**Comment by benelan** [comment]
Done, thanks for the review!

**Review by epwalsh — APPROVED** [review]
LGTM!
